### ISSUE TITLE
2TH POST

### ISSUE THREAD

**Issue by markd2** [killpack/shrekanography#2]
MAYBE HAVE LIKE DIFFERENT PICTURES OF SHREK. MAYBE SOME WITH THE DONKEY OR IN OTHER COMPROMISING SITUATIONS. THEN WE CAN HAVE DOWNLOAD FLODERS WITH MANY PICTURES OF SHREK.

**Comment by killpack** [comment]
DEFINITELY PLAN TO HAVE DIFFERENT MANISHREKSTATIONS BECAUSE THIS WEBSITE IS LIKE AN ONION AS IT HAS LAYERS

**Comment by killpack** [comment]
MORE DIFFERENT SHREKS ARE ADDED ALTHOUGH THERE ARE ONLY THREE TOTAL AND THEY WILL BE CHOSEN FOR YOU RANDOMLY, BECAUSE
